version: '3.1'

services:
  dbmysql:
    container_name: dbmysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mvc
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306